version: '3.9'

networks:
    wallet:

volumes:
  pg_backend_data_volume:

services:
  postgres:
    image: postgres:latest
    container_name: ${POSTGRES_CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pg_backend_data_volume:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - wallet

  redis:
    image: redis:latest
    container_name: ${REDIS_CONTAINER_NAME}
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./redis-data:/var/lib/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    restart: unless-stopped
    tty: true
    stdin_open: true
    depends_on:
      - postgres
    networks:
      - wallet


  wallet_api:
    build: ../src
    container_name: wallet_api
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ../src:/app
    env_file:
      - .env
    networks:
      - wallet